[project]
name = "api-dados-publicos"
version = "0.1.0"
description = ""
authors = [
    {name = "jaedsonmacedo",email = "jaedsonnm@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
]

[tool.poetry]
packages = [{include = "api_dados_publicos", from = "src"}]

[tool.poetry.scripts]
ola = "scripts.ola_mundo:main"
algo = "modelos.algo:algo"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "black (>=26.10.0,<27.0.0)",
    "flake8 (>=7.4.1,<8.0.0)"
]
